[package]
name = "railbreaker-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.3"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.43"
